### ISSUE TITLE
The 'rancher' provisioner could not be found

### ISSUE THREAD

**Issue by jmreicha** [nextrevision/rancheros-vagrant#1]
Receive the following message on first `vagrant up` if the rancher provisioner Vagrant plugin isn't installed first.

```
Checking and installing vagrant plugins
Bringing machine 'rancher-server-01' up with 'virtualbox' provider...
Bringing machine 'rancher-agent-01' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The 'rancher' provisioner could not be found.
```

It fixes itself if you rerun `vagrant up` but it would be nice to get everything set up and configured in one shot.

**Comment by nextrevision** [comment]
Will continue to search for a better solution, but I added a bit more verbosity to the installation step and decided to abort with a message before vagrant throws the error. This will hopefully make things a bit clearer in the short term. Thanks for catching that!

**Comment by jmreicha** [comment]
Thank you for the awesome project!
