### ISSUE TITLE
Can't provision agent

### ISSUE THREAD

**Issue by jmreicha** [nextrevision/rancheros-vagrant#5]
New issue.  Hopefully this is just something dumb I'm doing but when I attempt to bring up an agent it gets hung up when provisioning.  I haven't had a chance to really dig in to this yet so it might be user error.

Here's the log output, it never gets past SSH auth method.

```
vagrant up rancher-agent-01                                                                                                                                   jmreicha@aboutmes-MacBook-Pro
Bringing machine 'rancher-agent-01' up with 'virtualbox' provider...
==> rancher-agent-01: Importing base box 'rancherio/rancheros'...
==> rancher-agent-01: Matching MAC address for NAT networking...
==> rancher-agent-01: Checking if box 'rancherio/rancheros' is up to date...
==> rancher-agent-01: Setting the name of the VM: rancheros-vagrant_rancher-agent-01_1464051006374_64764
==> rancher-agent-01: Fixed port collision for 22 => 2222. Now on port 2200.
==> rancher-agent-01: Clearing any previously set network interfaces...
==> rancher-agent-01: Preparing network interfaces based on configuration...
    rancher-agent-01: Adapter 1: nat
    rancher-agent-01: Adapter 2: hostonly
==> rancher-agent-01: Forwarding ports...
    rancher-agent-01: 22 (guest) => 2200 (host) (adapter 1)
==> rancher-agent-01: Running 'pre-boot' VM customizations...
==> rancher-agent-01: Booting VM...
==> rancher-agent-01: Waiting for machine to boot. This may take a few minutes...
    rancher-agent-01: SSH address: 127.0.0.1:2200
    rancher-agent-01: SSH username: rancher
    rancher-agent-01: SSH auth method: private key
```

Eventually Vagrant times out but I am never able to SSH to the client host.

Thanks again for the awesome project, I'm writing a blog post about how to use it right now with plenty of links.  Let me know if there is anything you want me to link or plug in the post.

**Comment by nextrevision** [comment]
Thanks! I haven't seen this using it locally, what version of vagrant and virtualbox do you have?

**Comment by jmreicha** [comment]
It's strange, it just started happening this evening after trying the new changes.

 * `vagrant version: Installed Version: 1.8.1`
 * `virtualbox version: 5.0.14r105127`

I'll keep playing around with it.

**Comment by jmreicha** [comment]
I changed the rancher agent VM to use CoreOS instead of RancherOS and it booted up.  I think maybe there is something wrong with the RancherOS image I am using to provision the VM?  I'm done for now but will look at it more tomorrow.

**Comment by jmreicha** [comment]
Figured it out.  I was allocating 256MB to the server, which apparently isn't enough for RancherOS.

**Comment by nextrevision** [comment]
Ahh good to know, I'm going to update the docs to point this out.

**Comment by jmreicha** [comment]
One other caveat to note.  I haven't been able to get the rancher server container to load with less than 1024MB of memory so it might be worth noting that as well.
